- hosts: master
  become: yes
  become_user: ubuntu
  tasks:
    - name: setup traefik ingress controller
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/rlzh/cs754-p3/master/setup/k8s/object-definitions/traefik-rbac.yaml
        kubectl apply -f https://raw.githubusercontent.com/rlzh/cs754-p3/master/setup/k8s/object-definitions/traefik-deployment.yaml