apiVersion: "nuclio.io/v1"
kind: NuclioFunction
spec:
  env:
    - name: RMQ_HOST
      value: "10.38.194.7"
    - name: RMQ_PORT
      value: 5672
    - name: RMQ_USER
      value: nuclio
    - name: RMQ_PASS
      value: nuclio
    - name: REDUCE_TOPIC_PREFIX
      value: tasks.reduce.
    - name: NUM_REDUCERS
      value: 3
  handler: map:entry_point
  runtime: python:2.7
  replicas: 1
  minReplicas: 1
  maxReplicas: 100
  targetCPU: 10
  triggers:
    mapTrigger:
      kind: "http"
      attributes:
        port: 32001
    rmqTrigger:
      max_workers: 100
      kind: "rabbit-mq"
      url: "amqp://nuclio:nuclio@10.38.194.7:5672"
      attributes:
        topics:
        - tasks.map.#
        exchangeName: "mapred_exchange"
  build:
    commands:
    - "apk update"
    - "apk add py-pip"
    - "pip install pika"
    # - "pip install hdfs"
