apiVersion: "nuclio.io/v1"
kind: NuclioFunction
spec:
  env:
    - name: RMQ_HOST
      value: "10.32.128.199"
    - name: RMQ_PORT
      value: 5672
    - name: RMQ_USER
      value: nuclio
    - name: RMQ_PASS
      value: nuclio
    - name: REDUCE_TOPIC_PREFIX
      value: tasks.reduce.
    - name: NUM_REDUCERS
      value: 3
    - name: EXCHANGE_NAME
      value: mapred_exchange
  handler: map:entry_point
  runtime: python:3.6
  replicas: 1
  # minReplicas: 1
  # maxReplicas: 10
  # targetCPU: 5
  triggers:
    mapTrigger:
      # workerAvailabilityTimeoutMilliseconds: 50000
      kind: "http"
      attributes:
        port: 30000
    rmqTrigger:
      kind: "rabbit-mq"
      url: "amqp://nuclio:nuclio@10.32.128.199:5672"
      attributes:
        topics:
        - tasks.map.#
        exchangeName: "mapred_exchange"
  build:
    commands:
    - "apt update"
    - "pip install pika"
    - "pip install hdfs"
