apiVersion: "nuclio.io/v1"
kind: NuclioFunction
spec:
  env:
  handler: reduce:entry_point
  runtime: python:2.7
  replicas: 1
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 10
  triggers:
    rmqTrigger:
      kind: "rabbit-mq"
      url: "amqp://nuclio:nuclio@10.38.194.7:5672"
      attributes:
        topics: ["tasks.reduce.#"]
        exchangeName: "mapred_exchange"
    debugTrigger:
      maxWorkers: 4
      kind: "http"
      attributes:
        port: 32001
  build:
    commands:
    - "apk update"
    - "apk add py-pip"
    - "pip install pika"
    # - "pip install pydoop"    