apiVersion: "nuclio.io/v1"
kind: NuclioFunction
spec:
  env:
  handler: reduce:entry_point
  runtime: python:3.6
  replicas: 1
  triggers:
    rmqTrigger:
      maxWorkers: 1
      kind: "rabbit-mq"
      url: "amqp://nuclio:nuclio@10.38.194.7:5672"
      attributes:
        topics: ["tasks.reduce.#"]
        exchangeName: "mapred_exchange"
    httpTrigger:
      maxWorkers: 1
      kind: "http"
      attributes:
        port: 32002
  build:
    commands:
    - "apt update"
    - "pip install pika"
    - "pip install hdfs"
