- hosts: all
  become: yes
  tasks:
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: install ssh
      apt:
        name: ssh
        state: present
        update_cache: true
        force_apt_get: true

    - name: install pip
      apt:
        name: python-pip
        state: present
        update_cache: true
        force_apt_get: true
    
    - name: install java
      apt:
        name: openjdk-8-jdk-headless
        state: present
        update_cache: true
        force_apt_get: true

    - name: install mrjob
      become: yes
      become_user: ubuntu
      shell: sudo pip install mrjob


